version: "3"

services:
  db:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=AdminPassword123
      - POSTGRES_DB=chat

  backend:
    environment:
      - DB_HOST=db
      - DB_USERNAME=postgres
      - DB_NAME=chat
      - DB_PORT=5432
      - DB_PASSWORD=AdminPassword123
    build: .
    command: bash -c "cd gada_chat_service && cd chat_service && alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 5555 --reload"
    volumes:
      - .:/code
    ports:
      - "5555:5555"
    depends_on:
      - db
