"""change db schema

Revision ID: 122ac7058390
Revises: 6e03d8bc80bb
Create Date: 2022-04-12 00:53:08.852278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '122ac7058390'
down_revision = '6e03d8bc80bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
