"""change db schema

Revision ID: 6e03d8bc80bb
Revises: cdacce5864f8
Create Date: 2022-04-12 00:51:12.564441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e03d8bc80bb'
down_revision = 'cdacce5864f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('buyer_id', sa.String(), nullable=True),
    sa.Column('seller_id', sa.String(), nullable=True),
    sa.Column('channel_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_channel_name'), 'channel', ['channel_name'], unique=False)
    op.create_index(op.f('ix_channel_id'), 'channel', ['id'], unique=False)
    op.drop_table('room')
    op.drop_constraint('user_username_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_username_key', 'user', ['username'])
    op.create_table('room',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('buyer_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('seller_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('channel_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='room_pkey')
    )
    op.drop_index(op.f('ix_channel_id'), table_name='channel')
    op.drop_index(op.f('ix_channel_channel_name'), table_name='channel')
    op.drop_table('channel')
    # ### end Alembic commands ###
