"""Remove channel name and add buyer, seller name

Revision ID: 7d586605006f
Revises: 19c49dbba843
Create Date: 2022-05-24 11:11:57.120565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d586605006f'
down_revision = '19c49dbba843'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel', sa.Column('buyer_name', sa.String(), nullable=True))
    op.add_column('channel', sa.Column('seller_name', sa.String(), nullable=True))
    op.drop_index('ix_channel_channel_name', table_name='channel')
    op.create_index(op.f('ix_channel_buyer_name'), 'channel', ['buyer_name'], unique=False)
    op.create_index(op.f('ix_channel_seller_name'), 'channel', ['seller_name'], unique=False)
    op.drop_column('channel', 'channel_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel', sa.Column('channel_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_channel_seller_name'), table_name='channel')
    op.drop_index(op.f('ix_channel_buyer_name'), table_name='channel')
    op.create_index('ix_channel_channel_name', 'channel', ['channel_name'], unique=False)
    op.drop_column('channel', 'seller_name')
    op.drop_column('channel', 'buyer_name')
    # ### end Alembic commands ###
