"""altering table name

Revision ID: 95b9965300c9
Revises: d39d6e7f5780
Create Date: 2022-04-19 11:24:01.587526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95b9965300c9'
down_revision = 'd39d6e7f5780'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('related_question',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_related_answer', sa.Integer(), nullable=True),
    sa.Column('question', sa.String(), nullable=True),
    sa.Column('is_automate_reply', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('related_question')
    # ### end Alembic commands ###
