"""add getstream id

Revision ID: be68c1494ea8
Revises: 122ac7058390
Create Date: 2022-04-12 00:54:39.621659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be68c1494ea8'
down_revision = '122ac7058390'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('getstream_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'getstream_id')
    # ### end Alembic commands ###
