"""add qna journey

Revision ID: caaf880e0f16
Revises: 95b9965300c9
Create Date: 2022-04-19 12:39:45.032969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caaf880e0f16'
down_revision = '95b9965300c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qna_journey',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('base_question', sa.Column('trigger_action', sa.String(), nullable=True))
    op.add_column('related_answer', sa.Column('trigger_action', sa.String(), nullable=True))
    op.drop_column('related_answer', 'id_base_question')
    op.drop_column('related_question', 'id_related_answer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('related_question', sa.Column('id_related_answer', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('related_answer', sa.Column('id_base_question', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('related_answer', 'trigger_action')
    op.drop_column('base_question', 'trigger_action')
    op.drop_table('qna_journey')
    # ### end Alembic commands ###
