"""add  table for question, related question, and answer

Revision ID: d39d6e7f5780
Revises: 8a1b8ba7e47f
Create Date: 2022-04-13 15:19:14.025259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd39d6e7f5780'
down_revision = '8a1b8ba7e47f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(), nullable=True),
    sa.Column('is_automate_reply', sa.Boolean(), nullable=True),
    sa.Column('context', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_base_question_id'), 'base_question', ['id'], unique=False)
    op.create_table('related_answer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('answer', sa.String(), nullable=True),
    sa.Column('id_base_question', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('answer')
    op.drop_index('ix_question_id', table_name='question')
    op.drop_table('question')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_automate_reply', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='question_pkey')
    )
    op.create_index('ix_question_id', 'question', ['id'], unique=False)
    op.create_table('answer',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('answer', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='answer_pkey')
    )
    op.drop_table('related_answer')
    op.drop_index(op.f('ix_base_question_id'), table_name='base_question')
    op.drop_table('base_question')
    # ### end Alembic commands ###
